spring.application.name=reservasajedrez
# Canviar la ruta de la interfície d'usuari de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# Canviar la ruta de la definició JSON de l'API
springdoc.api-docs.path=/api-docs

#spring.data.mongodb.uri=mongodb+srv://Pol:1234@cluster0.ovj4k4q.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=provaDB

##crear índexs a la BD
#spring.data.mongodb.auto-index-creation=true

jwt.secret=12345678901234567890123456789012
jwt.expiration-ms=86400000